### ISSUE TITLE
User credentials cannot be modified

### ISSUE THREAD

**Issue by l4t3b0** [elkninja/elastic-stack-docker-part-one#1]
First of all I would like to thank you these docker configuration files. This has great added value to be able to set up and run a full ELK environment for developers in minutes 👏

I have successfully installed it in my local docker environment and it works great unless I make modifications in my .env file for the passwords.

Unfortunately the configuration files of the beats has the hardcoded password 'changeme' and therefore it cannot be modified.

Would be nice if you could fix it

**Comment by elkninja** [comment]
Thanks @l4t3b0!  I've [created a branch](https://github.com/elkninja/elastic-stack-docker-part-one/tree/feature/update-env-vars) with those changes.  Would you mind pulling down that branch and testing a password change to make sure it works for you?

**Comment by l4t3b0** [comment]
wow

I was not expecting an answer In so short time 😃

I just made a short test, but I can confirm, that it is working.
I can login to Kibana with modified elastic password and metricbeat keeps on sending the data

great job 👍

thanks
