### ISSUE TITLE
Exited setup service

### ISSUE THREAD

**Issue by RamizVa1iyev** [elkninja/elastic-stack-docker-part-one#11]
After starting docker container setup service exited
The logs of setup service: 
Creating CA
Archive:  config/certs/ca.zip
   creating: config/certs/ca/
  inflating: config/certs/ca/ca.crt  
  inflating: config/certs/ca/ca.key  
Creating certs
Archive:  config/certs/certs.zip
   creating: config/certs/es01/
  inflating: config/certs/es01/es01.crt  
  inflating: config/certs/es01/es01.key  
   creating: config/certs/kibana/
  inflating: config/certs/kibana/kibana.crt  
  inflating: config/certs/kibana/kibana.key  
Setting file permissions
Waiting for Elasticsearch availability
Setting kibana_system password

!

What can be reason of that?

**Comment by kweidi** [comment]
This is normal behaviour, as explained in the blog : 

![image](https://github.com/elkninja/elastic-stack-docker-part-one/assets/119486486/79a7a212-f1a7-4b0b-838e-a349aa678fd5)

**Comment by kweidi** [comment]
I think this is normal behaviour, as explained in the blog : 

![image](https://github.com/elkninja/elastic-stack-docker-part-one/assets/119486486/79a7a212-f1a7-4b0b-838e-a349aa678fd5)

**Comment by RamizVa1iyev** [comment]
Thanks for replay.
