### ISSUE TITLE
Containers exiting - no entry point OR strict.perms not found

### ISSUE THREAD

**Issue by HussainFaruk** [elkninja/elastic-stack-docker-part-one#16]
When composing up, logstash, metricbeat and filebeat fail
<img width="559" alt="image" src="https://github.com/elkninja/elastic-stack-docker-part-one/assets/73562626/d75eb0cc-d587-480d-bfb8-f7db03238929">

All 3 containers exit for the same reason
<img width="607" alt="image" src="https://github.com/elkninja/elastic-stack-docker-part-one/assets/73562626/aae59eaa-cd5a-4743-bfe7-b0923781bd78">

**Comment by HussainFaruk** [comment]
Running on mac intel

**Comment by yakeeliuliu** [comment]
same issue here - Windows Docker Desktop

**Comment by ehogeweg** [comment]
Reproducible on Ubuntu-22.04
```
2023/11/26 23:35:59 Setting 'xpack.monitoring.enabled' from environment.
/usr/local/bin/docker-entrypoint: line 30: exec: strict.perms=false: not found
```

**Comment by yakeeliuliu** [comment]
saw the pull request, another workaround is
`command: ["filebeat", "-e", "--strict.perms=false"]`

**Comment by elkninja** [comment]
syntax was bad for filebeat/metricbeat, and nonexistent for logstash.
i updated the strict-perms syntax and it should work now.  removed it for logstash.
let me know if you still have issues.
