### ISSUE TITLE
startup error (strict.perms=false not found)

### ISSUE THREAD

**Issue by naizhao** [elkninja/elastic-stack-docker-part-one#19]
filebeat01-1    | /usr/local/bin/docker-entrypoint: line 25: exec: strict.perms=false: not found
filebeat01-1 exited with code 127
logstash01-1    | 2023/12/27 09:07:31 Setting 'xpack.monitoring.enabled' from environment.
logstash01-1    | /usr/local/bin/docker-entrypoint: line 30: exec: strict.perms=false: not found
metricbeat01-1  | /usr/local/bin/docker-entrypoint: line 25: exec: strict.perms=false: not found
logstash01-1 exited with code 127
metricbeat01-1 exited with code 127

**Comment by naizhao** [comment]
it seems like extra space added, the correct one is remove the space like
```
    command:
      -strict.perms=false
```

**Comment by naizhao** [comment]
Also, the 
```
command: 
    - strict.perms=false
```
section in logstash01 must be removed, otherwise the following error will occur:

```
logstash01-1    | ERROR: Unrecognised option '-s'
logstash01-1    |
logstash01-1    | See: 'bin/logstash --help'
logstash01-1    | [FATAL] 2023-12-27 10:10:57.077 [main] Logstash - Logstash stopped processing because of an error: (SystemExit) exit
logstash01-1    | org.jruby.exceptions.SystemExit: (SystemExit) exit
logstash01-1    | 	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:808) ~[jruby.jar:?]
logstash01-1    | 	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:767) ~[jruby.jar:?]
logstash01-1    | 	at RUBY.run(/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/clamp-1.0.1/lib/clamp/command.rb:138) ~[?:?]
logstash01-1    | 	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]
logstash01-1 exited with code 1
```

**Comment by DanTheMinotaur** [comment]
I found in the [docs](https://www.elastic.co/guide/en/beats/metricbeat/current/command-line-options.html) it's a flag. Adding `--` let my container start. 

```yaml
    command:
      - --strict.perms=false
```

**Comment by fulldeck** [comment]
this solved it for me

command: filebeat -e -strict.perms=false

**Comment by elkninja** [comment]
sorry ive been AFK!  i updated the strict perms for metricbeat and filebeat.  i also removed the strict perms for logstash since i dont think that command existed the way i thought it did.

**Comment by elkninja** [comment]
i'll mark this one as closed unless someone continues to see an issue with those changes.

**Comment by elkninja** [comment]
sorry ive been AFK! i updated the strict perms for metricbeat and filebeat. i also removed the strict perms for logstash since i dont think that command existed the way i thought it did.

i'll mark this one as closed.  we can open a new one if anything else crops up.
