### ISSUE TITLE
Feature request: Fleet server

### ISSUE THREAD

**Issue by l4t3b0** [elkninja/elastic-stack-docker-part-one#2]
Hi

I believe my request is far beyond the original scope of your project, but I consider this GitHub repo as a great start for elastic developers.

Adding a fleet server to the docker compose would be awesome

**Comment by elkninja** [comment]
Hey, @l4t3b0!  I'm actively working on "Part Two" of that blog post which will build on top of this one.  It will include things like Fleet Server and Agent setup, along with other Integrations, APM, and additional features.

**Comment by l4t3b0** [comment]
Sounds great 🥳

When can we expect that?

**Comment by captain-hindsightt** [comment]
Eagerly waiting for the Fleet Server and Agent setup. Generating service token and incorporating it into docker-compose.yml without restarting the containers is a bit challenging at the moment.

**Comment by elkninja** [comment]
@l4t3b0 , @captain-hindsightt  - I just found that another team at Elastic has done a similar project last year and has a container approach that includes Fleet/Agent already.  Check out https://www.elastic.co/security-labs/the-elastic-container-project and see if that will help you in the meantime!

**Comment by captain-hindsightt** [comment]
@elkninja Thanks for the update, I will definitely check it out. ✌️
