### ISSUE TITLE
I have corrected a few issues and have the docker-compose project working

### ISSUE THREAD

**Issue by fulldeck** [elkninja/elastic-stack-docker-part-one#21]
I have corrected a few issues and have the docker-compose project working.
I have committed the changes to my master branch in my repo.

https://github.com/fulldeck/elastic-stack-docker-part-one/tree/master

**Comment by elkninja** [comment]
Nice, @fulldeck!  I have just updated mine to change the strict-perms for metricbeat/filebeat, and removed the one for logstash.  i think the strict perms primarily applicable for docker on windows.
I was under the impression that the service name would automatically become the hostname of the container.  ive never had comms issues between the containers, but if this makes things more consistent then great!
