### ISSUE TITLE
Elasticsearch Exited (137)

### ISSUE THREAD

**Issue by man20820** [elkninja/elastic-stack-docker-part-one#8]
run on ubuntu 20.04, 22.04
spec: 2core cpu 8gb ram

~# docker -v
Docker version 24.0.4, build 3713ee1

~# docker compose version
Docker Compose version v2.19.1

docker logs:
{"@timestamp":"2023-07-16T18:52:24.587Z", "log.level": "INFO", "message":"adding index lifecycle policy [synthetics-synthetics.http-default_policy]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.xpack.ilm.action.TransportPutLifecycleAction","trace.id":"73ee250f29ad38b64403dec513c3306f","elasticsearch.cluster.uuid":"-KUubkq5Q0m4mYhf_BiGng","elasticsearch.node.id":"UGU5g84rQNaHDOIFPGX0JA","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2023-07-16T18:52:27.631Z", "log.level": "INFO", "message":"[.ds-metricbeat-8.7.1-2023.07.16-000001/sF0X39DOR_W9ptBFBieBbA] update_mapping [_doc]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.metadata.MetadataMappingService","elasticsearch.cluster.uuid":"-KUubkq5Q0m4mYhf_BiGng","elasticsearch.node.id":"UGU5g84rQNaHDOIFPGX0JA","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2023-07-16T18:52:30.507Z", "log.level": "INFO", "message":"adding index lifecycle policy [synthetics-synthetics.icmp-default_policy]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.xpack.ilm.action.TransportPutLifecycleAction","trace.id":"73ee250f29ad38b64403dec513c3306f","elasticsearch.cluster.uuid":"-KUubkq5Q0m4mYhf_BiGng","elasticsearch.node.id":"UGU5g84rQNaHDOIFPGX0JA","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}

ERROR: Elasticsearch exited unexpectedly

**Comment by elkninja** [comment]
this will happen if you're ingesting/searching on the cluster more than the configured memory will allow.  
you may want to try raising the ES_MEM var in the .env file.
