### ISSUE TITLE
Exiting: error loading config file: config file ("filebeat.yml") can only be writable by the owner but the permissions are "-rwxrwxrwx"

### ISSUE THREAD

**Issue by kmgalanakis** [elkninja/elastic-stack-docker-part-one#9]
I don't know if this is a Windows-specific error but when running this, the filebeat container fails with the following error:

```
Exiting: error loading config file: config file ("filebeat.yml") can only be writable by the owner but the permissions are "-rwxrwxrwx" (to fix the permissions use: 'chmod go-w /usr/share/filebeat/filebeat.yml')
```

The same thing applies to the metricbeat container

```
Exiting: error loading config file: config file ("metricbeat.yml") can only be writable by the owner but the permissions are "-rwxrwxrwx" (to fix the permissions use: 'chmod go-w /usr/share/metricbeat/metricbeat.yml')
```

A workaround for this is to add the `command: --strict.perms=false -e` line in the `docker-compose.yml` file for each one of the "problematic" containers,

Would you be interested in a PR with such fix?

**Comment by CawaKharkov** [comment]
Sane issues on ubuntu, so its not windows specific error:
`elk-metricbeat01-1  | Exiting: error loading config file: config file ("metricbeat.yml") must be owned by the user identifier (uid=0) or root`

**Comment by kweidi** [comment]
Same topic as in issue https://github.com/elkninja/elastic-stack-docker-part-one/issues/4

**Comment by elkninja** [comment]
implemented the strict-perms for filebeat and metricbeat - albeit broken at first - but now fixed! 😄

**Comment by elkninja** [comment]
implemented the strict-perms for filebeat and metricbeat - albeit broken at first - but now fixed! 😄
